[package]
name = "mtos-docker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
fetch-data = "0.2.0"
filedb-ng = "0.1.1"
semver = "1.0.23"
serde = { version = "1.0.210", features = ["derive"] }
serde_yaml = "0.9.34"
sha256 = "1.5.0"
traits = {path = "libs/traits", version = "*"}
[workspace]
members = ["package_manager", "libs/colors", "libs/traits", "helpers/shapkg"]

[[bin]]
name = "pm"
path = "package_manager/src/main.rs"

[lib]
name = "colors"
path = "libs/colors/src/lib.rs"
