name: Build the thing
on: 
    schedule:
        - cron: "@weekly"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        container:
            image: alpine:latest
        steps:
            - name: Prepare the environment
              run: apk update; apk add alpine-sdk clang cmake pkgconf
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                  targets: x86_64-unknown-linux-musl
            - name: Compile and release
              uses: rust-build/rust-build.action@v1.4.5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}