on:
    push:
    workflow_dispatch:
    schedule:
        - cron: "20 20 20 20 *"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        container:
            image: alpine:latest
        steps:
            - name: Prepare the environment
              run: apk update; apk add alpine-sdk clang cmake pkgconf bash curl
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                  targets: x86_64-unknown-linux-musl
            - name: Compile and release
              run: cargo build --release --workspace
            - uses: rickstaa/action-create-tag@v1
              id: "tag_create"
              with:
                tag: "nightly"
                tag_exists_error: false
                message: "Nightly release of MatuushOS"
            - uses: actions/upload-artifact@v4
              with:
                  name: pm
                  path: |
                      target/x86_64-unknown-linux-musl/release/pm
                      target/x86_64-unknwon-linux-musl/release/mkrepo
                      target/x86_64-unknown-linux-musl/release/shapkg
            - uses: softprops/action-gh-release@v2
              with:
                  files: |
                      target/x86_64-unknown-linux-musl/release/pm
                      target/x86_64-unknwon-linux-musl/release/mkrepo
                      target/x86_64-unknown-linux-musl/release/shapkg